### ISSUE TITLE
Not checking the 'dead' entity flag while iterating over entities.

### ISSUE THREAD

**Issue by luauser32167** [tsherif/space-shooter.c#16]
As far as I understand, dead entities are only filtered before calling the drawing/rendering functions. While iterating over entities we don't seem to be skipping those with their `->dead[i]` flag set. I am not sure if that's correct though.

In the function `src/game/game.c/mainGame` we call `simWorld`, which checks for collisions between player bullets and enemies (i.e it sets the `->dead[i]` flag), later 'mainGame' also calls `simPlayer` which checks for collisions between the player and the enemies using the `checkPlayerCollision` function. But the `checkPlayerCollision` function doesn't skip "dead" enemies, which makes it possible for "dead" enemies to collide with the player.

**Comment by tsherif** [comment]
Hi! Thanks for looking into this, and sorry for the late reply. This is intentional. Essentially the way of thinking about the batch updates is that entities are considered “alive” for the entirety of the step they’re being processed in. They aren’t really dead until they’re filtered out of the entity array at the end of the step. The `dead` flag can be thought of as `willBeDeadOnNextStep`. If I allowed entities to die mid-step, there would be an order-dependence on the collision tests, i.e. checking player/enemy collisions first vs. bullet/enemy collisions first would result in different behavior.
